### ISSUE TITLE
Download dependencies

### ISSUE THREAD

**Issue by cVoltic** [OEUM/PySpectra#1]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\iy3827\Anaconda3\envs\Server_env\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iy3827\\AppData\\Local\\Temp\\pip-install-igb4sja5\\spc\\setup.py'"'"'; __file__='"'"'C:\\Users\\iy3827\\AppData\\Local\\Temp\\pip-install-igb4sja5\\spc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\iy3827\AppData\Local\Temp\pip-install-igb4sja5\spc\pip-egg-info'
         cwd: C:\Users\iy3827\AppData\Local\Temp\pip-install-igb4sja5\spc\
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\site-packages\ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\iy3827\AppData\Local\Temp\pip-install-igb4sja5\spc\setup.py", line 4, in <module>
        use_setuptools()
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\site-packages\ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\site-packages\ez_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\site-packages\ez_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 569, in error
        return self._call_chain(*args)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 503, in _call_chain
        result = func(*args)
      File "C:\Users\iy3827\Anaconda3\envs\Server_env\lib\urllib\request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    **urllib.error.HTTPError: HTTP Error 403: SSL is required**
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by OEUM** [comment]
Changed setup.py to spc_spectra instead of spc.
Change reader  to import spc_spectra as spc.
Commit : 3e2b75bc0ebf5c000843d13826097865624ec7c4
