### ISSUE TITLE
pip install pyspectra issue

### ISSUE THREAD

**Issue by nash5202** [OEUM/PySpectra#6]
Hi @OEUM ,

Many thanks for making the pyspectra package for the spectroscopy data. 
I am trying to install "pyspectra" package using `pip install pyspectra` and I am running into the following issue:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting pyspectra
  Obtaining dependency information for pyspectra from https://files.pythonhosted.org/packages/34/cd/072c984e3a3130f1f1dd9423c8e1a97b312cb09f616ebcd8ba09b9b0f03d/pyspectra-0.0.1.2-py3-none-any.whl.metadata
  Using cached pyspectra-0.0.1.2-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy in c:\users\xxxxxxx\appdata\roaming\python\python312\site-packages (from pyspectra) (2.0.1)
Requirement already satisfied: pandas in c:\users\xxxxxxx\appdata\roaming\python\python312\site-packages (from pyspectra) (2.2.2)
Collecting spc-spectra (from pyspectra)
  Using cached spc_spectra-0.4.0.tar.gz (8.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
 
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-build-env-8kv7q1mr\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-build-env-8kv7q1mr\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-build-env-8kv7q1mr\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-build-env-8kv7q1mr\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-install-c9mzyqzr\spc-spectra_1ba43b1382364f4b9466156033124bcb\spc_spectra\__init__.py", line 3, in <module>
          from .spc import File
        File "C:\Users\xxxxxxx\AppData\Local\Temp\pip-install-c9mzyqzr\spc-spectra_1ba43b1382364f4b9466156033124bcb\spc_spectra\spc.py", line 10, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
 
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
 
note: This error originates from a subprocess, and is likely not a problem with pip.
```

As you can see, `numpy` is installed but I am still getting `ModuleNotFoundError: No module named 'numpy'` error. Can you please have a look at this issue and suggest if there is something that I am doing wrong in installing pyspectra package. I have tried to diagnose the problem for a day now and any help is highly appreciated. 

Thank you.

**Comment by quentin-bml** [comment]
Hi,

I'm having the same issue.

@nash5202 have you ever found a solution ?
